language: en

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "LanguageModelFeaturizer"
    model_name: "bert"
    model_weights: "bert-base-uncased"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "DIETClassifier"
    epochs: 100
    random_seed: 42
    entity_recognition: True
    constrain_similarities: True
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100
    retrieval_intent: "faq"
    clean_up_tokenization_spaces: True
    constrain_similarities: True


policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 20
    evaluate_every_number_of_epochs: 5
    constrain_similarities: true
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: RulePolicy
    epochs: 20
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
    enable_fallback_prediction: True

assistant_id: 20231202-221250-mode-flour