language: en

pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: SpacyTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: LexicalSyntacticFeaturizer
  - name: "SpacyFeaturizer"
  - name: RegexEntityExtractor
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: true
  - name: DIETClassifier
    epochs: 25
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.2

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 20
    evaluate_every_number_of_epochs: 5
    constrain_similarities: true
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: RulePolicy
    epochs: 20
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
    enable_fallback_prediction: True

assistant_id: 20231202-221250-mode-flour